[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 25
headless = true

[theme]
base = "dark"
primaryColor = "#4f46e5"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#e2e8f0"
font = "sans serif"
